### ISSUE TITLE
Mikrotik RouterOS API

### ISSUE THREAD

**Issue by kmorin18** [pavel-odintsov/fastnetmon#860] opened 2020-10-04 15:10 UTC
Hello,

When looking at Mikrotik's API documentation, I can see that the authentication method has changed:
https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

This change notes a new method since 6.45.1 (2019-07-01) and the last update of FNM's routeros_api.php was in 2016.

Is it possible that this is causing API authentication problems?

Regards,

**Comment by pavel-odintsov** [comment] 2020-10-11 00:19
Hello!

Yes, it may cause such problems. I'll share your feedback with plugin author.

**Comment by elmaxid** [comment] 2020-10-12 17:48
Hello

Yes, this is the cause. I push a fix to this issue:

https://github.com/pavel-odintsov/fastnetmon/pull/862

M.

**Comment by pavel-odintsov** [comment] 2020-10-12 18:00
I've merged fix! Can you try downloading latest version, please https://github.com/pavel-odintsov/fastnetmon/pull/862?

**Comment by pavel-odintsov** [comment] 2020-10-18 11:58
Feel free to reopen it if it does not solve your problem!

**Closed by pavel-odintsov** 2020-10-18 11:58 UTC
