### ISSUE TITLE
Incompatibility with pf_ring 6.5.0 and 6.6.0

### ISSUE THREAD

**Issue by papage** [pavel-odintsov/fastnetmon#601] opened 2016-11-11 09:13 UTC
Hi,

I'm running fastnetmon with a /16 network and it ignores almost all the packets. I'm assuming fastnetmon does not think that packets belong to /16 network and the "Not processed packets" increases rapidly. Of course packets belong to the /16 network. Packets are 802.1q tagged.

Strangely, it reports a few IPs (with false trafffic).

I'm using pfring_zc with a mirror port on a Centos7.0 server with a  pfring installation from the ntopng repo (though i don't really know what the fastnetmon.pl script installed).

Note:  I'm opening ens160 and not zc:esn160. When I put zc:esn160 in the configuration, fastnetmon reports:
[ERROR] pfring_zc_open_device error Socket operation on non-socket Please check that device is up and not already used.

pfring_zc though seems to be ok:
root# pfcount -i ens160
---
Absolute Stats: [3'172'422 pkts total][0 pkts dropped][0.0% dropped]
[3'172'422 pkts rcvd][2'201'411'658 bytes rcvd][507'299.29 pkt/sec][2'816.20 Mbit/sec]
---
Actual Stats: [115'451 pkts rcvd][252.90 ms][456'513.91 pps][2.52 Gbps]

or 
zcount -i zc:ens160
---
Absolute Stats: 890'841 pkts (0 drops) - 641'022'281 bytes
Actual Stats: 451'906.31 pps (0.00 drops) - 2.56 Gbps
---

Am i doing something wrong, or is it a fastnetmon bug?

Thanx,
Sp

Configuration is:
logging:local_syslog_logging = off
logging:remote_syslog_logging = off
logging:remote_syslog_server = 10.10.10.10
logging:remote_syslog_port = 514
enable_ban = off
process_incoming_traffic = on
process_outgoing_traffic = on
ban_details_records_count = 500
ban_time = 1900
unban_only_if_attack_finished = on
enable_subnet_counters = on
networks_list_path = /etc/networks_list  # one /16 network
white_list_path = /etc/networks_whitelist
check_period = 1
enable_connection_tracking = off
ban_for_pps = on
ban_for_bandwidth = on
ban_for_flows = off
threshold_pps = 20000
threshold_mbps = 100
threshold_flows = 3500
threshold_tcp_mbps = 100000
threshold_udp_mbps = 100000
threshold_icmp_mbps = 100000
threshold_tcp_pps = 100000
threshold_udp_pps = 100000
threshold_icmp_pps = 100000
ban_for_tcp_bandwidth = off
ban_for_udp_bandwidth = off
ban_for_icmp_bandwidth = off
ban_for_tcp_pps = off 
ban_for_udp_pps = off
ban_for_icmp_pps = off
mirror = on
pfring_sampling_ratio = 1
mirror_netmap = off
mirror_snabbswitch = off
mirror_afpacket = off
interfaces = ens160
netmap_sampling_ratio = 1
netmap_read_packet_length_from_ip_header = off
pcap = off
netflow = off
sflow = off
enable_pf_ring_zc_mode = on
interfaces = ens160
average_calculation_time = 1
average_calculation_time_for_subnets = 20
netflow_port = 2055
netflow_host = 0.0.0.0
netflow_sampling_ratio = 1
netflow_divide_counters_on_interval_length = off
sflow_port = 6343
sflow_host = 0.0.0.0
notify_script_path = /usr/local/bin/notify_about_attack.sh
notify_script_pass_details = on
collect_attack_pcap_dumps = off
process_pcap_attack_dumps_with_dpi = off
redis_enabled = on
redis_port = 6379
redis_host = 127.0.0.1
redis_prefix = mydc1
mongodb_enabled = off
pfring_hardware_filters_enabled = off
exabgp = off
gobgp = off
graphite = off
monitor_local_ip_addresses = on
pid_path = /var/run/fastnetmon.pid
cli_stats_file_path = /tmp/fastnetmon.dat
enable_api = off
sort_parameter = packets
max_ips_in_list = 15

FastNetMon 1.1.3 master git-94f4947e87753b8be193ca54d17dac24cac599fb Pavel Odintsov: stableit.ru
IPs ordered by: packets
Incoming traffic             8 pps      0 mbps      0 flows
x.y.4.130                2 pps      0 mbps      0 flows
x.y.4.143                2 pps      0 mbps      0 flows
x.y.4.22                 1 pps      0 mbps      0 flows
x.y.4.133                0 pps      0 mbps      0 flows
x.y.4.71                 0 pps      0 mbps      0 flows
x.y.4.92                 0 pps      0 mbps      0 flows
x.y.4.149                0 pps      0 mbps      0 flows
x.y.4.144                0 pps      0 mbps      0 flows
x.y.4.117                0 pps      0 mbps      0 flows
x.y.4.170                0 pps      0 mbps      0 flows
x.y.4.171                0 pps      0 mbps      0 flows
x.y.4.1                  0 pps      0 mbps      0 flows
x.y.4.66                 0 pps      0 mbps      0 flows
x.y.4.200                0 pps      0 mbps      0 flows

Outgoing traffic             8 pps      0 mbps      0 flows
x.y.4.143                3 pps      0 mbps      0 flows
x.y.4.130                3 pps      0 mbps      0 flows
x.y.4.1                  1 pps      0 mbps      0 flows
x.y.4.133                0 pps      0 mbps      0 flows
x.y.4.71                 0 pps      0 mbps      0 flows
x.y.4.92                 0 pps      0 mbps      0 flows
x.y.4.149                0 pps      0 mbps      0 flows
x.y.4.144                0 pps      0 mbps      0 flows
x.y.4.22                 0 pps      0 mbps      0 flows
x.y.4.170                0 pps      0 mbps      0 flows
x.y.4.117                0 pps      0 mbps      0 flows
x.y.4.171                0 pps      0 mbps      0 flows
x.y.4.66                 0 pps      0 mbps      0 flows
x.y.4.200                0 pps      0 mbps      0 flows

Internal traffic            84 pps      0 mbps

Other traffic                0 pps      0 mbps

Screen updated in:              0 sec 4724 microseconds
Traffic calculated in:          0 sec 31052 microseconds
Total amount of IPv6 packets related to our own network: 0
Not processed packets: 449057 pps

PF_RING ZC in queue statistics
Received:       15571796
Sent:           0
Dropped:        0
Dropped:        0.00 %

PF_RING ZC out queue statistics
Received:       15571734
Sent:           15571797
Dropped:        0
Dropped:        0.00 %

Subnet load:
x.y.0.0/16     pps in: 9        out: 10       mbps in: 0     out: 0
x.y.47.118/32  pps in: 0        out: 0        mbps in: 0     out: 0
x.y.47.26/32  pps in: 0        out: 0        mbps in: 0     out: 0

# If you want to solve your issue please read following information below

First of all, please check following steps:
* Do you have latest FastNetMon version? If not, please upgrade to 1.1.3 version.
* Do we have similar tickets already? Please check [bug tracker](https://github.com/pavel-odintsov/fastnetmon/issues) and [Mailing list](https://groups.google.com/forum/#!forum/fastnetmon) about similar issues.

If it does not help, please fill information below:
* Your operating system name and version?
* Please attach your /etc/fastnetmon.conf configuration file
* What capture engine are you using: netflow, sflow, miror?
* If you are using netflow or sflow, please specify version, vendor name, model name and firmware of agent device.  
* Please attach /var/log/fastnetmon.log

Then please describe your issue as detailed as possible! Thanks you :)

**Comment by pavel-odintsov** [comment] 2016-11-11 09:27
Hello!

Have you enabled ZC mode explicitly?

```
enable_pf_ring_zc_mode = on
```

?

**Comment by pavel-odintsov** [comment] 2016-11-11 09:29
Oh, sorry, I see, it's enabled. Very strange.

**Comment by papage** [comment] 2016-11-11 09:37
Hi!

Thanx for the fast response.  Some more data:
[root ~]# lsmod | grep pf_ring
pf_ring              1224429  1 
[root ~]# lsmod | grep ixg
ixgbe_zc              302523  0 
ptp                    19231  1 ixgbe_zc
vxlan                  41228  1 ixgbe_zc

yum packages that were installed before FNM install script:
cento.x86_64                            1.3.161109-133                 @ntop    
ixgbe-zc.noarch                         4.1.5.985-dkms                 @ntop-noarch
n2disk.x86_64                           2.7.161109-4743                @ntop    
nbox.noarch                             2.5.0-553                      @ntop-noarch
nprobe.x86_64                           7.5.161109-5471                @ntop    
ntopng.x86_64                           2.5.161109-1681                @ntop    
ntopng-data.noarch                      2.5.161109-1681                @ntop-noarch
pfring.x86_64                           6.5.0-985                      @ntop    
pfring-dkms.noarch                      6.5.0-985                      @ntop-noarch

Cheers,
Sp

**Comment by at0rvk** [comment] 2016-11-17 12:44
Hi,

I had the same issue, I found that fastnetmon doesn't work properly with pf_ring 6.5.0. Downgrading to 6.0.3 (the version installed by fastnetmon_install.pl) fixes the problem for me. Of course fastnetmon should be fixed to work with current versions of pf_ring 6.5.0

**Comment by atonkyra** [comment] 2017-02-01 15:00
+1

**Comment by pavel-odintsov** [comment] 2017-02-01 20:24
PF_RING has bunch of different versions and I could not port tool to each new release so fast. Netmap also stable option and works pretty well.

Also you could native (free! And fast!) linux way to capture traffic: af_packet.

**Comment by at0rvk** [comment] 2017-02-02 12:32
With af_packet only one interface can be captured in fastnetmon :( I need to capture four interfaces:

> [WARN] We support only single interface for AF_PACKET, sorry!

I can't use netmap, because then I can't also capture the same traffic with nprobe to create my precious netflow data.

So I have to stick with PF_RING 6.0.3.

**Comment by pavel-odintsov** [comment] 2017-02-02 22:41
Yes, multiple interface mode is a bit.. complicated for af_packet.

**Comment by pavel-odintsov** [comment] 2017-06-24 12:03
Hello!

I was able to reproduce issue with PF_RING 6.6.0.

You could do same. Just download fastnetmon_install.pl and apply following fixes.

Replace lines:
```
my $pf_ring_version = '6.0.3';
my $pf_ring_url = "https://github.com/ntop/PF_RING/archive/v$pf_ring_version.tar.gz";
```

By:
```
my $pf_ring_version = '6.6.0';
my $pf_ring_url = "https://github.com/ntop/PF_RING/archive/$pf_ring_version.tar.gz";
```

And replace `9fb8080defd1a079ad5f0097e8a8adb5bc264d00` by `79ff86e48df857e4e884646accfc97bdcdc54b04`.

**Comment by pavel-odintsov** [comment] 2017-06-24 12:04
I started FNM, enabled mirror mode and downloaded file http://ovh.net/files/1Gb.dat using wget.

Then I got zero counters at fastnetmon_client and following number of errors:
```
Not processed packets: 0 pps
Packets received:       591
Packets dropped:        12221
Packets dropped:        2067.9 %
```

**Comment by pavel-odintsov** [comment] 2017-06-24 12:14
I raised ticket to PF_RING project because I have no idea what happened :(

**Comment by pavel-odintsov** [comment] 2017-06-24 20:55
Hello!

I introduced complete support for PF_RING 6.6.0 in official install script:
```
sudo perl fastnetmon_install.pl --use-modern-pf-ring 
```

Please install FNM this way and check issue again. Thanks!

**Closed by pavel-odintsov** 2017-06-24 20:55 UTC
Labels: enhancement
