### ISSUE TITLE
FNM client showing 0 flows.

### ISSUE THREAD

**Issue by deivisfp** [pavel-odintsov/fastnetmon#693] opened 2017-11-26 15:59 UTC
Hello,

First of all, FNM is amazing, congrats!
I'm using lastest version of git at Ubuntu 16.04 and it's working like a charm. I just observed that "fastnetmon_client" do not count the flow column (screenshot attached). Could figure out why?
=)

- FNM 1.1.3 lastest master git
- Ubuntu 16.04
- Netflow v5 on Mikrotik ROS 6.40.2
- FNM conf file attached
- Screenshot of FNM client attached

Thankyou!
=)

[fastnetmon.txt](https://github.com/pavel-odintsov/fastnetmon/files/1504025/fastnetmon.txt)
![flows 0s](https://user-images.githubusercontent.com/4823566/33241794-04363126-d2b2-11e7-8588-371b5cd9d0b5.png)

**Comment by openbsod** [comment] 2017-11-26 20:37
Hello.

Imo not a bug.. just because 0 flows recv ( IN )

![fnm-flow](https://user-images.githubusercontent.com/19532554/33244093-1e357eb0-d302-11e7-8794-bc4b8bf40c5f.png)

**Comment by pavel-odintsov** [comment] 2017-11-26 20:50
Hello!

It should for Netflow.

Could you try this option https://github.com/pavel-odintsov/fastnetmon/blob/master/src/fastnetmon.conf#L50 ?

**Comment by deivisfp** [comment] 2017-11-26 21:20
Hello!

Thanks for replying so quickly!
With connection tracking enabled I can see some flows. It realy needs to be enable? I'm worried about CPU...
=)
![flows 0s-2](https://user-images.githubusercontent.com/4823566/33244465-ce80787a-d2de-11e7-8cc1-13c9ea174061.png)

**Comment by pavel-odintsov** [comment] 2017-11-26 21:31
It's only one way to get flow per second information. CPU consumption should not be huge.

**Comment by deivisfp** [comment] 2017-11-26 21:40
Thank you guys!

**Comment by pavel-odintsov** [comment] 2017-12-19 12:23
Closing as an issue was fixed

**Closed by pavel-odintsov** 2017-12-19 12:23 UTC
